import GoalProbabilityCalculator from "@/components/calculator/GoalProbabilityCalculator";
import CalculatorJsonLd from "@/components/seo/CalculatorJsonLd";
import { Article, Disclaimer, FaqItem, FaqSection, PageHeader, RelatedCalculators, SectionCard } from "@/components/ui/Shared";
import { buildMetadata } from "@/lib/metadata";

const title = "투자 목표달성확률 계산기";
const description = "목표금액과 투자 기간, 월 투자금, 기대수익률과 변동성을 입력해 목표를 달성한 시뮬레이션 비율과 필요한 월 투자금을 계산합니다.";
export const metadata = buildMetadata({ title, description, path: "/goal-probability-calculator", keywords: ["목표달성확률 계산기", "목표 금액 계산기", "필요 월 투자금", "몬테카를로"] });
const faqs = [{ question: "목표달성확률이 80%면 실제로 성공할 확률이 80%인가요?", answer: "아닙니다. 입력한 수익률·변동성·물가 가정과 결과 재현 번호로 생성한 시나리오 중 목표를 넘은 비율입니다." }, { question: "필요 월 투자금은 어떻게 계산하나요?", answer: "같은 시장 경로에서 최종 자산이 월 투자금에 대해 선형이라는 성질을 이용해, 원하는 비율의 경로가 목표를 넘는 최소 월 투자금을 정확히 역산합니다." }, { question: "세금과 수수료도 포함되나요?", answer: "아니요. 수익률은 배당 재투자 총수익 가정이며 세금과 거래비용은 반영하지 않습니다." }];
export default function GoalProbabilityPage() { return <main className="min-h-screen bg-slate-50 pb-20 text-slate-900"><CalculatorJsonLd title={title} description={description} path="/goal-probability-calculator" faqs={faqs} /><PageHeader badge="재무 목표" title={title} description={description} /><div className="mx-auto max-w-5xl px-6 py-12 md:px-8 md:py-16"><GoalProbabilityCalculator /><SectionCard><Article title="목표달성확률 계산기란?"><p>하나의 고정 수익률 대신 다양한 수익률 경로를 사용해 현재 투자 계획이 목표금액을 넘는 시나리오 비율을 계산합니다. 원하는 목표 비율에 필요한 월 투자금도 같은 경로에서 역산합니다.</p></Article><Article title="결과를 해석하는 방법"><p>목표 비율을 높일수록 필요한 월 투자금이 커집니다. 결과는 미래를 예측하거나 보장하지 않으며, 입력 가정이 바뀌면 결과도 달라집니다.</p></Article></SectionCard><FaqSection title="자주 묻는 질문 (FAQ)">{faqs.map((faq) => <FaqItem key={faq.question} question={faq.question} answer={faq.answer} />)}</FaqSection><RelatedCalculators links={[{ href: "/dca-calculator", title: "적립식 투자 시뮬레이션", desc: "장기 자산 분포와 팬 차트 확인" }, { href: "/compound-interest-calculator", title: "복리 계산기", desc: "고정 수익률 기준 최종 금액 계산" }]} /><Disclaimer /></div></main>; }
