"use client";
import { useCallback, useMemo, useState } from "react";
import { AdvancedPanel, CalculatorCard, CalculatorLayout, InputEffectNote, InputField, PercentileNote, ResultCard, ResultDetail, ResultHighlight, ResultNote, simulationIssueText } from "@/components/ui/Shared";
import { useMonteCarlo } from "@/hooks/useMonteCarlo";
import { buildFireInput, fireSuccessRate, type FireValues } from "@/lib/fire";

type Fields = Record<"seed"|"paths"|"currentAge"|"retirementAge"|"planToAge"|"currentAssets"|"monthlyContribution"|"monthlyExpenses"|"expectedReturn"|"volatility"|"inflation", string>;
const INITIAL: Fields = { seed:"", paths:"10000", currentAge:"", retirementAge:"", planToAge:"", currentAssets:"", monthlyContribution:"", monthlyExpenses:"", expectedReturn:"", volatility:"", inflation:"" };
const won=(v:number)=>Number.isFinite(v)?new Intl.NumberFormat("ko-KR",{maximumFractionDigits:0}).format(v):"-";
const pct=(v:number)=>Number.isFinite(v)?`${(v*100).toFixed(1)}%`:"-";

export default function FireCalculator(){
  const [f,setF]=useState<Fields>(INITIAL); const {status,result,progress,error,run,cancel}=useMonteCarlo(0);
  const set=useCallback(<K extends keyof Fields>(k:K,v:Fields[K])=>setF(p=>({...p,[k]:v})),[]);
  const values=useMemo<FireValues>(()=>({seed:Number(f.seed),paths:Number(f.paths),currentAge:Number(f.currentAge),retirementAge:Number(f.retirementAge),planToAge:Number(f.planToAge),currentAssets:Number(f.currentAssets),monthlyContribution:Number(f.monthlyContribution),monthlyExpenses:Number(f.monthlyExpenses),expectedReturnPercent:Number(f.expectedReturn),volatilityPercent:Number(f.volatility),inflationPercent:Number(f.inflation)}),[f]);
  const hasAgeInput=f.currentAge!==""||f.retirementAge!==""||f.planToAge!=="";
  const localError=!hasAgeInput?null:values.retirementAge<=values.currentAge?"은퇴 나이는 현재 나이보다 커야 합니다.":values.planToAge<=values.retirementAge?"계획 종료 나이는 은퇴 나이보다 커야 합니다.":null;
  const start=useCallback(()=>{if(!localError)run(buildFireInput(values));},[localError,run,values]);
  const progressPct=progress&&progress.total?progress.completed/progress.total*100:0;
  const success=result?fireSuccessRate(result):0;
  const resultPhases=result?.input.cashFlow.phases;
  const retirementMonth=resultPhases?.[0]?.toMonth??0;
  const retirementBand=result?.bands.find(b=>b.month===retirementMonth);
  const resultMonthlyExpenses=Math.abs(resultPhases?.[1]?.monthlyAmount??0);
  const fireTarget=resultMonthlyExpenses*12*25;
  return <CalculatorLayout>
      <CalculatorCard title="FIRE 계획 조건" description="은퇴 전 적립과 은퇴 후 물가연동 생활비 인출을 하나의 시뮬레이션으로 연결합니다.">
    <div className="grid gap-4 sm:grid-cols-2"><InputField id="fire-age" label="현재 나이" type="number" value={f.currentAge} onChange={e=>set("currentAge",e.target.value)} unit="세" placeholder="예: 35"/><InputField id="fire-retire" label="은퇴 목표 나이" type="number" value={f.retirementAge} onChange={e=>set("retirementAge",e.target.value)} unit="세" placeholder="예: 55"/><InputField id="fire-end" label="계획 종료 나이" type="number" value={f.planToAge} onChange={e=>set("planToAge",e.target.value)} unit="세" placeholder="예: 90"/><InputField id="fire-assets" label="현재 투자자산" type="number" value={f.currentAssets} onChange={e=>set("currentAssets",e.target.value)} unit="원" placeholder="예: 100000000"/><InputField id="fire-save" label="은퇴 전 월 투자금" type="number" value={f.monthlyContribution} onChange={e=>set("monthlyContribution",e.target.value)} unit="원" placeholder="예: 2000000"/><InputField id="fire-spend" label="현재 기준 월 생활비" type="number" value={f.monthlyExpenses} onChange={e=>set("monthlyExpenses",e.target.value)} unit="원" placeholder="예: 3000000"/><InputField id="fire-return" label="연평균 수익률 (CAGR)" type="number" value={f.expectedReturn} onChange={e=>set("expectedReturn",e.target.value)} unit="%" placeholder="예: 7" hint="이 투자가 1년에 평균 몇 %씩 불어난다고 가정할지 정합니다." help="예를 들어 7을 넣으면 ‘매년 7%씩 복리로 불어난다고 치고’ 계산합니다. 매년 정확히 7%가 난다는 뜻이 아니라 긴 기간의 평균이 7%라는 가정입니다.\n\n이 값을 올리면 예상 결과가 전체적으로 커집니다. 실제 수익률은 알 수 없으므로 값을 바꿔가며 결과가 얼마나 달라지는지 보는 용도로 쓰는 편이 낫습니다." /><InputField id="fire-vol" label="수익률이 흔들리는 정도 (변동성)" type="number" value={f.volatility} onChange={e=>set("volatility",e.target.value)} unit="%" placeholder="예: 15" hint="수익률이 해마다 얼마나 출렁이는지 정합니다. 이 값이 이 계산기의 핵심입니다." help="0을 넣으면 매년 똑같은 수익률이 나서 일반 복리 계산기와 결과가 같아집니다. 15를 넣으면 어떤 해는 크게 오르고 어떤 해는 떨어지는 상황을 만들어 계산합니다. 그래서 결과가 하나의 숫자가 아니라 범위로 나옵니다.\n\n이 값을 올리면 결과의 폭이 넓어집니다. 좋은 쪽 결과도 커지지만 나쁜 쪽은 더 나빠지고 목표를 넘지 못할 가능성도 함께 커집니다." /><InputField id="fire-inflation" label="연 물가상승률" type="number" value={f.inflation} onChange={e=>set("inflation",e.target.value)} unit="%" placeholder="예: 2" hint="물가가 매년 얼마나 오른다고 볼지 정합니다." help="20년 뒤의 1억 원은 지금의 1억 원과 가치가 다릅니다. 이 값을 넣으면 결과를 지금 돈으로 치면 얼마인지로 바꿔 보여줍니다.\n\n한국은행의 중기 물가안정목표는 연 2%입니다. 실제 상승률은 시기에 따라 이보다 높을 수 있으니 값을 올려서도 확인해 보세요. 이 값을 올리면 물가를 반영한 결과가 작아집니다." /></div>
    {(localError||error)?<div role="alert" className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">{localError??error?.issues?.map(i=><p key={`${i.field}-${i.message}`}>{simulationIssueText(i)}</p>)??error?.message}</div>:null}
    <div className="flex gap-3"><button type="button" onClick={start} disabled={status==="running"||!!localError} className="min-h-11 rounded-2xl bg-slate-900 px-5 py-3 font-semibold text-white disabled:opacity-50">FIRE 시뮬레이션</button><button type="button" onClick={cancel} disabled={status!=="running"} className="min-h-11 rounded-2xl border border-slate-300 px-5 py-3 font-semibold disabled:opacity-40">취소</button></div>{status==="running"?<div className="h-2 rounded bg-slate-200"><div className="h-full bg-slate-900" style={{width:`${progressPct}%`}}/></div>:null}
  
      <AdvancedPanel>
        <div className="grid gap-4 sm:grid-cols-2"><InputField id="fire-paths" label="가상 미래를 몇 번 만들지 (경로 수)" type="number" value={f.paths} onChange={e=>set("paths",e.target.value)} unit="개" placeholder="예: 10000" hint="서로 다른 미래를 몇 개 만들어볼지 정합니다." help="이 계산기는 미래를 하나만 예측하지 않고 서로 다른 미래를 수천~수만 개 만들어 결과가 어떻게 퍼지는지를 봅니다. 숫자를 늘리면 결과가 더 안정적이지만 계산이 오래 걸립니다." /><InputField id="fire-seed" label="결과 재현 번호" type="number" value={f.seed} onChange={e=>set("seed",e.target.value)} placeholder="예: 20260824" grouping={false} hint="같은 번호를 넣으면 언제 계산해도 똑같은 결과가 나옵니다." help="결과를 캡처해두거나 남에게 보여줄 때 이 번호가 같으면 상대도 똑같은 화면을 볼 수 있습니다. 신경 쓰지 않아도 되는 값입니다." /></div>
      </AdvancedPanel>
      <InputEffectNote />
      </CalculatorCard>{result?<><CalculatorCard title="FIRE 시뮬레이션 결과" description={`${result.meta.pathsRun.toLocaleString("ko-KR")}개 시나리오 · ${(result.input.months/12).toFixed(0)}년 계획`}><ResultHighlight label="계획 종료 전 자산이 소진되지 않은 시나리오" value={pct(success)} tone={success>=0.8?"positive":"negative"}/><div className="grid gap-4 sm:grid-cols-2"><ResultDetail label="은퇴 시점 자산 중앙값(현재 가치)" value={won(retirementBand?.p50??0)} unit="원"/><ResultDetail label="계획 종료 자산 중앙값(현재 가치)" value={won(result.terminal.p50)} unit="원"/><ResultDetail label="소진 시나리오 비율" value={pct(result.depletion?.rate??0)}/><ResultDetail label="25배 참고 금액" value={won(fireTarget)} unit="원"/></div><ResultNote><PercentileNote /><p>25배 금액은 연 생활비의 25배를 단순 표시한 참고값이며, 이 계산기의 성공 판정은 각 경로에서 생활비를 인출한 뒤 계획 종료 전 자산이 소진되는지로 결정합니다.</p></ResultNote></CalculatorCard><CalculatorCard title="보수적 결과 범위"><div className="grid gap-4 sm:grid-cols-2"><ResultDetail label="은퇴 시점 보수적인 경우 (하위 10%)" value={won(retirementBand?.p10??0)} unit="원"/><ResultDetail label="종료 시점 보수적인 경우 (하위 10%)" value={won(result.terminal.p10)} unit="원"/><ResultDetail label="종료 시점 좋은 경우 (상위 10%)" value={won(result.terminal.p90)} unit="원"/><ResultDetail label="사용 시드" value={String(result.meta.seed)}/></div></CalculatorCard><CalculatorCard title="가정과 주의사항"><ul className="list-disc space-y-2 pl-5 text-sm text-slate-600"><li>은퇴 후 생활비는 현재 금액을 기준으로 입력하며 매년 물가만큼 증가합니다.</li>{result.meta.warnings.map(w=><li key={w}>{w}</li>)}</ul></CalculatorCard></>:<ResultCard title="FIRE 시뮬레이션 결과" isValid={false} emptyMessage="값을 입력하고 시뮬레이션을 실행하면 결과가 표시됩니다."/>}</CalculatorLayout>;
}
